## Importing the library

In [2]:
import numpy as np

### Creating numpy arrays:


<b>1. Using a list</b>

In [3]:
lst = [1,2,3,4,5]
type(lst)

list

In [4]:
my_array = np.array(lst)
my_array

array([1, 2, 3, 4, 5])

In [5]:
type(my_array)

numpy.ndarray

<b>2. Using arange()</b>

In [6]:
my_arr = np.arange(0,99,2)
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
type(my_arr)

numpy.ndarray

<b>3. Using zeros()</b>

In [8]:
my_arr = np.zeros(shape=(5,5))

In [9]:
my_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
type(my_arr)

numpy.ndarray

<b>4. Using ones()</b>

In [11]:
my_arr = np.ones(shape=(5,5))
my_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
my_arr*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [13]:
type(my_arr)

numpy.ndarray

### Creating random values

In [23]:
np.random.seed(101)

In [24]:
arr = np.random.randint(0,100,10)

In [25]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

<b>Maximum:</b>

In [28]:
arr.max() # Value

95

In [30]:
arr.argmax() # Its position

0

<b>Minimum:</b>

In [31]:
arr.min() # Value

9

In [32]:
arr.argmin() #Its position

7

<b>Shape</b>

In [34]:
arr.shape

(10,)

<b>Reshape</b>

In [35]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

### Indexing

In [41]:
mat = np.random.randint(0,100,50).reshape(10,5)

In [42]:
mat

array([[35, 30, 10, 60, 20],
       [27,  8, 86, 26, 87],
       [46, 47, 54, 86,  9],
       [45,  2, 18, 58, 92],
       [11, 10, 94, 35, 28],
       [ 3, 83, 84, 47, 14],
       [69, 60, 69, 51,  6],
       [88, 71, 68, 23, 35],
       [79, 98, 67, 82, 57],
       [77, 46,  3, 46, 29]])

<b> The basic syntax for indexing is:<br>
    arr[r,c]
</b>

In [43]:
mat[1,2] # Retrieves the third element of 2 row ie, 86

86

<b> Slicing in Indexing </b>

In [45]:
mat[0:2,0:3] # Retrieves row 0 and 1 and Column 0 to 2 in each of the selected row

array([[35, 30, 10],
       [27,  8, 86]])

### Copying a numpy array

In [47]:
mat_copy = mat.copy()
mat_copy

array([[35, 30, 10, 60, 20],
       [27,  8, 86, 26, 87],
       [46, 47, 54, 86,  9],
       [45,  2, 18, 58, 92],
       [11, 10, 94, 35, 28],
       [ 3, 83, 84, 47, 14],
       [69, 60, 69, 51,  6],
       [88, 71, 68, 23, 35],
       [79, 98, 67, 82, 57],
       [77, 46,  3, 46, 29]])

In [48]:
mat_copy[0:2,:] = 0
mat_copy

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [46, 47, 54, 86,  9],
       [45,  2, 18, 58, 92],
       [11, 10, 94, 35, 28],
       [ 3, 83, 84, 47, 14],
       [69, 60, 69, 51,  6],
       [88, 71, 68, 23, 35],
       [79, 98, 67, 82, 57],
       [77, 46,  3, 46, 29]])

In [49]:
mat

array([[35, 30, 10, 60, 20],
       [27,  8, 86, 26, 87],
       [46, 47, 54, 86,  9],
       [45,  2, 18, 58, 92],
       [11, 10, 94, 35, 28],
       [ 3, 83, 84, 47, 14],
       [69, 60, 69, 51,  6],
       [88, 71, 68, 23, 35],
       [79, 98, 67, 82, 57],
       [77, 46,  3, 46, 29]])